#!/bin/bash -e
# regenerate apache redmine mysql password

. /etc/default/inithooks

DB_USER=redmine_apache
CONF_DIR=/etc/apache2/conf

APACHE_RUNNING=$(/etc/init.d/apache2 status > /dev/null; echo $?)

# regen mysql password
PASSWORD=$(mcookie)
CONF=$CONF_DIR/svn-redmine.conf
sed -i "s|RedmineDbPass.*|RedmineDbPass \"${PASSWORD}\"|" $CONF
CONF=$CONF_DIR/git-redmine.conf
sed -i "s|RedmineDbPass.*|RedmineDbPass \"${PASSWORD}\"|" $CONF
CONF=$CONF_DIR/hg-redmine.conf
sed -i "s|RedmineDbPass.*|RedmineDbPass \"${PASSWORD}\"|" $CONF
CONF=$CONF_DIR/bzr-redmine.conf
sed -i "s|RedmineDbPass.*|RedmineDbPass \"${PASSWORD}\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=$DB_USER --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug, may not be needed?)
rm -f /var/lib/mysql/ib_logfile*

if [ "$APACHE_RUNNING" == "0" ]; then
    /etc/init.d/apache2 restart
fi
