production:
  deny_delete: false
  auto_create: true
  force_repository: false
  pre_create: /usr/local/bin/pre-create.sh
  post_create: /usr/local/bin/post-create.sh
  pre_delete: /usr/local/bin/pre-delete.sh
  post_delete: /usr/local/bin/post-delete.sh
  max_repos: 0
  only_creator: false
  allow_add_local: false
  allow_pickup: false
  svn:
    path: /srv/repos/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
    append: trunk
  git:
    path: /srv/repos/git
    git: /usr/lib/git-core/git
    options: --bare
    url: git
    update_server_info: true
    git_ext: false
  mercurial:
    path: /srv/repos/hg
    hg: /usr/bin/hg
    url: hg
  bazaar:
    path: /srv/repos/bzr
    bzr: /usr/bin/bzr
    init: init-repository
    log_encoding: UTF-8
    url: bzr

development:
